### PR TITLE
添加【嘉嘉的博客】

### LINKED ISSUE #1164: 嘉嘉的博客
### 网站名称

嘉嘉的博客

### 网站网址

https://blog.jiajia.ml/

### 徽标位置

顶部和底部

### 内容方向

C++、Python编程经验，辅以生活趣事

### 请确认一下事项

- [x] 我已确认以上事项

### PR DESCRIPTION
**Pull request by justin-jiajia**
fixed #1164

### CODE REVIEW

**Comment by linlinzzo** [comment]
move to #1166

**Comment by HuaJi114** [comment]
hello

**Comment by linlinzzo** [comment]
Hi.

**Comment by A7103** [comment]
Are you two brothers? @justin-jiajia and @HuaJi114 :trollface:

**Comment by justin-jiajia** [comment]
No, why?

**Comment by linlinzzo** [comment]
Just because your avatars are too similar.

**Pull request closed without merging**
